# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec — build Cerberus as a standalone windowed program.

    Windows:  pyinstaller cerberus.spec      -> dist/Cerberus/Cerberus.exe
    macOS:    pyinstaller cerberus.spec      -> dist/Cerberus.app
    Linux:    pyinstaller cerberus.spec      -> dist/Cerberus/Cerberus

Entry point is desktop.py (boots uvicorn on a private loopback port + opens a
native webview window). This is a per-OS build: run it on the OS you are
targeting (CI uses a windows-latest runner for the .exe).

Build profile — controls how much is bundled:

    CERBERUS_DESKTOP_PROFILE=full   (default)  bundle everything incl. ML deps
    CERBERUS_DESKTOP_PROFILE=lean              exclude torch/transformers/CUDA

"lean" produces a small, robust executable and expects the heavy ML + sandbox
work to run on the (Docker) server configured in the in-app settings. "full" is
offline-capable but large; pair it with the CPU-only torch wheel (the Windows
CI installs torch from the CPU index) so we do not ship multi-GB of CUDA.

`onedir` (COLLECT) is used rather than `onefile`: it starts faster, plays nicer
with the WebView2 backend, and NSIS packages the folder into an installer.
"""
import os
import sys
from PyInstaller.utils.hooks import collect_submodules, collect_data_files

block_cipher = None

PROFILE = os.environ.get("CERBERUS_DESKTOP_PROFILE", "full").strip().lower()
LEAN = PROFILE == "lean"

# ── Data files shipped inside the bundle ────────────────────────────────────
# The frontend and default config travel with the app. Runtime state does NOT:
# desktop.py redirects CERBERUS_DATA_DIR to a per-user writable location, so the
# `data/` tree is intentionally not bundled (it is created/seeded at first run).
datas = [
    ("static", "static"),
    ("config", "config"),
    ("docs/cerberus.jpg", "docs"),           # source image for the window icon
]
# Window-icon assets, generated by the build script into desktop_assets/ before
# PyInstaller runs. Optional — desktop.py degrades to the default icon.
if os.path.isdir("desktop_assets"):
    datas.append(("desktop_assets", "desktop_assets"))

# opensandbox ships templates/metadata the SDK loads at runtime.
datas += collect_data_files("opensandbox", include_py_files=False)

# ── Hidden imports ──────────────────────────────────────────────────────────
# Routes are wired with explicit `from routes.x import ...`, so static analysis
# finds most of them; collect_submodules guarantees the long tail (and any
# conditionally-imported blueprint) is included.
hiddenimports = []
for pkg in ("routes", "services", "core", "src", "gateway", "mcp_servers",
            "integrations", "desktop_bridge", "trading", "companion"):
    try:
        hiddenimports += collect_submodules(pkg)
    except Exception:
        pass
# Third-party modules PyInstaller commonly under-collects. chromadb pulls its
# telemetry submodules (e.g. chromadb.telemetry.product.posthog) dynamically, so
# static analysis misses them and the vector store fails to init without this.
for pkg in ("uvicorn", "opensandbox", "pydantic", "pydantic_settings",
            "email_validator", "webview", "chromadb"):
    try:
        hiddenimports += collect_submodules(pkg)
    except Exception:
        pass

# ── Excludes ────────────────────────────────────────────────────────────────
# Always drop build/test-only and clearly-unused heavyweight modules.
excludes = ["pytest", "tests", "IPython", "notebook", "tkinter"]
if LEAN:
    # Push all heavy ML to the server in lean builds.
    excludes += [
        "torch", "torchvision", "torchaudio", "transformers", "accelerate",
        "safetensors", "tokenizers", "onnxruntime", "fastembed", "nltk",
        "sympy", "networkx",
        # CUDA runtime wheels pulled in by the default torch build.
        "nvidia", "triton",
    ]

a = Analysis(
    ["desktop.py"],
    pathex=["."],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

_ICON = None
for _cand in ("desktop_assets/cerberus.ico", "desktop_assets/cerberus.icns"):
    if os.path.exists(_cand):
        _ICON = _cand
        break

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="Cerberus",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,                 # UPX corrupts some native .pyd / WebView2 libs
    console=False,             # windowed app, no terminal
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=_ICON,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="Cerberus",
)

# macOS: wrap the COLLECT output in a .app bundle (build-only target; not signed).
if sys.platform == "darwin":
    app = BUNDLE(
        coll,
        name="Cerberus.app",
        icon=_ICON,
        bundle_identifier="com.itseliias.cerberus",
    )
